
Below are the selected plots:

```{r plot1, fig.height=5,echo=FALSE,message=FALSE,warning=FALSE}
par(mar = c(4, 4, 1, 1))

 plotdata <- subset(newbuoydata,SiteName==input$site & DateTime >= input$dates[1] & DateTime<= input$dates[2])

ggplot(data=plotdata,aes(x=plotdata$Chlorophyll,y=plotdata[,input$param]),color='green')+ geom_point() +
      geom_smooth() + xlab("Chlorophyll") + ylab(input$param)+ ggtitle("Input Parameter and Chlorophyll Comparison")
```

```{r model, echo=FALSE, message=FALSE, warning= FALSE, results='hide'}

  plotdata <- subset(newbuoydata,SiteName==input$site &
                       DateTime >= input$dates[1] &
                       DateTime<= input$dates[2])
  mod <- lm(plotdata$Chlorophyll~plotdata[,input$param])
  modsummary <- summary(mod)
  return(modsummary)
```

R-Squared between Chlorophyll and,`r input$param`, during this timeframe: `r modsummary$r.squared`

```{r plot2, fig.height=5,echo=FALSE,message=FALSE,warning=FALSE}
par(mar = c(4, 4, 1, 1))

plotdata <- subset(newbuoydata,SiteName==input$site & DateTime >= input$dates[1] & DateTime<= input$dates[2])
    
    ggplot(data=plotdata,aes(x=plotdata$DateTime,y=plotdata[,input$param]),color='red')+ geom_point() + geom_smooth() + xlab("Time") + ylab(input$param) + ggtitle("Time Series Comparison")
```
Viewing water quality data at `r input$site` between `r input$dates[1]` and `r input$dates[2]`

```{r plot3, fig.height=5,echo=FALSE,message=FALSE,warning=FALSE}
par(mar = c(4, 4, 1, 1))

plotdata <- subset(newbuoydata,SiteName==input$site & DateTime >= input$dates[1] & 
                         DateTime<= input$dates[2])
    
    # Compute Linear Regression
    
    z <- plotdata$Chlorophyll
    x <- plotdata[,input$param]
    y <- plotdata[, input$param2]  
    
    fit <- lm(z ~ x + y)
    
    fitpoints <- predict(fit)
    
    # scatter plot with regression plane
    
    grid.lines = 26
    x.pred <- seq(min(x,na.rm = TRUE), max(x,na.rm = TRUE), length.out = grid.lines)
    y.pred <- seq(min(y,na.rm = TRUE), max(y,na.rm = TRUE), length.out = grid.lines)
    xy <- expand.grid( x = x.pred, y = y.pred)
    z.pred <- matrix(predict(fit, newdata = xy), 
                     nrow = grid.lines, ncol = grid.lines)
    
    fitpoints <- predict(fit)
    
    plot3 <- scatter3D(x, y, z, phi = 0, ticktype = "detailed", par(xpd=TRUE),
              zlab = "Chlorophyll", xlab = input$param, ylab = input$param2,  
              surf = list(x = x.pred, y = y.pred, z = z.pred,facets = NA), main = "Multiple Regression Model")
```

```{r model2, echo=FALSE, message=FALSE, warning= FALSE, results='hide'}

 plotdata <- subset(newbuoydata,SiteName==input$site &
                         DateTime >= input$dates[1] &
                         DateTime<= input$dates[2])
    
    x <- plotdata$Chlorophyll
    y <- plotdata[,input$param]
    z <- plotdata[, input$param2]  
    
    fitline <- lm(x ~ z + y)
    
    fitsummary <- summary(fitline)
    
    return(fitsummary)
```

R-Squared between Chlorophyll, `r input$param` and,`r input$param2`, during this timeframe: `r fitsummary$r.squared`